ALTER TABLE runs ADD COLUMN replay_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN replay_sha256 TEXT NOT NULL DEFAULT '';
CREATE TABLE replays (
 run_id TEXT PRIMARY KEY REFERENCES runs(id),
 data BLOB NOT NULL CHECK(length(data) BETWEEN 44 AND 1010000)
);
