"""Static export of original HLecture advice; no guest execution or emulator."""
import argparse
import hashlib
import json
import struct
from pathlib import Path

CANONICAL_SHA256 = "efda831f1212db54cc2e4ba53424fe390f91b2daabb07e93c1e389c3736d0335"
BASE = 0x0C020000

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("image", type=Path)
    parser.add_argument("--native", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--proof", type=Path, required=True)
    args = parser.parse_args()
    data = args.image.read_bytes()
    if hashlib.sha256(data).hexdigest() != CANONICAL_SHA256:
        raise ValueError("Canonical original image hash mismatch")
    def word(address): return struct.unpack_from("<I", data, address-BASE)[0]
    def text(address):
        begin = address-BASE
        end = data.index(0, begin, begin+512)
        return data[begin:end].decode("ascii")
    advice=[]
    for kind, (base, count) in enumerate([(0x0C338AEC,8),(0x0C338CB0,3),(0x0C338F08,6)]):
        rows=[]
        for index in range(count):
            address=base+index*16
            pointers=[word(address+j*4) for j in range(4)]
            rows.append({"row_address":address,"addresses":pointers,"text":[text(p) for p in pointers]})
        advice.append(rows)
    predicates=[[word(base+i*8+4) for i in range(count)] for base,count in [(0x0C337D44,8),(0x0C337D84,3),(0x0C337D9C,3)]]
    thresholds=[[word(base+course*36) for base in [0x0C2909A4,0x0C2909A8,0x0C2909AC,0x0C2909B0,0x0C2909B8,0x0C2909BC,0x0C2909C0]] for course in range(9)]
    replacements=[]
    for base,count in [(0x0C338FBC,3),(0x0C339048,4)]:
        replacements.append([{"address":word(base+i*4),"text":text(word(base+i*4))} for i in range(count)])
    section_counts=[word(0x0C339058+i*4) for i in range(9)]
    six_speed=[word(0x0C26BA9C+i*8) for i in range(35)]
    output=["// Generated by export_original_time_attack_analysis.py from SHA256 "+CANONICAL_SHA256,
            "// Original English spelling, punctuation and trailing spaces are retained."]
    for kind,rows in enumerate(advice):
        output.append("constexpr std::array<OriginalTimeAttackAdviceText,"+str(len(rows))+"> advice"+str(kind)+"{{")
        for row in rows:
            output.append("    {0x%08xu,{%s},{%s}},"%(row["row_address"],','.join("0x%08xu"%p for p in row["addresses"]),','.join(json.dumps(t) for t in row["text"])))
        output.append("}};")
    output.append("constexpr std::array<std::array<std::uint32_t,7>,9> thresholds{{")
    output.extend("    {%s},"%','.join("0x%08xu"%v for v in row) for row in thresholds)
    output.append("}};")
    for kind,values in enumerate(predicates): output.append("constexpr std::array<std::uint32_t,%d> predicates%d{%s};"%(len(values),kind,','.join("0x%08xu"%v for v in values)))
    output.append("constexpr std::array<unsigned,9> sectionCounts{%s};"%','.join(map(str,section_counts)))
    output.append("constexpr std::array<unsigned,35> sixSpeed{%s};"%','.join(map(str,six_speed)))
    for name,rows in zip(["circuit","mountain"],replacements):
        output.append("constexpr std::array<std::uint32_t,%d> %sAddresses{%s};"%(len(rows),name,','.join("0x%08xu"%row["address"] for row in rows)))
        output.append("constexpr std::array<std::string_view,%d> %sText{%s};"%(len(rows),name,','.join(json.dumps(row["text"]) for row in rows)))
    destination=args.native/"src/original_time_attack_analysis_tables.inc"
    destination.write_text('\n'.join(output)+'\n',encoding="utf-8")
    args.proof.mkdir(parents=True,exist_ok=True)
    manifest={"canonical_sha256":CANONICAL_SHA256,"advice_tables":advice,"predicate_addresses":predicates,"threshold_words":thresholds,"section_counts":section_counts,"six_speed":six_speed,"section_text":replacements,"generated_sha256":hashlib.sha256(destination.read_bytes()).hexdigest()}
    (args.proof/"analysis-source-data.json").write_text(json.dumps(manifest,indent=2)+'\n',encoding="utf-8")
    print("Exported17 original advice rows,7 section replacements,14 predicate addresses; no guest execution.")

if __name__ == "__main__": main()
