"""Reproduce the small original grid-table include; no original opcodes."""
import argparse
import hashlib
from pathlib import Path
import struct

def export(image_path, output):
    image = image_path.read_bytes()
    digest = "efda831f1212db54cc2e4ba53424fe390f91b2daabb07e93c1e389c3736d0335"
    if len(image) != 4194304 or hashlib.sha256(image).hexdigest() != digest:
        raise ValueError("Original grid export requires the canonical program")
    lines = ["// Generated by tools/export_original_start_grid.py from canonical image.",
             "// Source SHA256 " + digest, "// Original course order, direction, then grid slot; raw binary32 words."]
    for name, address in [("positions", 0x0C29EA34), ("directions", 0x0C29EBE4)]:
        lines.append(f"constexpr std::array<Words3,36> {name}{{{{")
        for row in range(36):
            words = struct.unpack_from("<3I", image, address - 0x0C020000 + row * 12)
            lines.append("    {" + ",".join(f"0x{word:08X}u" for word in words) + "},")
        lines.append("}};")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Exported864 unchanged bytes of original grid positions/directions as C++ constants")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    export(args.image, args.output)
