#!/usr/bin/env python3
"""Export immutable HLecture scalar/map tables from the verified original image.
Static data reads only. Does not decode or execute guest instructions.
"""
import argparse
import hashlib
from pathlib import Path
import struct

BASE = 0x0C020000
SHA = "efda831f1212db54cc2e4ba53424fe390f91b2daabb07e93c1e389c3736d0335"


def export(image, output):
    data = image.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA:
        raise ValueError("Unexpected original image SHA256")
    def words(address, count):
        return struct.unpack_from("<" + "I" * count, data, address - BASE)
    rows = []
    for course in range(9):
        threshold = words(0x0C2909B4 + course * 36, 1)
        corners = words(words(0x0C337F34 + course * 4, 1)[0], 12)
        matrix = words(words(0x0C338158 + course * 4, 1)[0], 16)
        sections = [words(words(0x0C33862C + (course * 3 + section) * 4, 1)[0], 12) for section in range(3)]
        ranges = words(0x0C3390C4 + course * 24, 6)
        start = words(0x0C33907C + course * 8, 2)
        lengths = words(0x0C29E2C0 + course * 12, 2)
        rows.append((threshold, corners, matrix, sections, ranges, start, lengths))
    def cpp(values):
        return "{" + ",".join(f"0x{x:08x}u" for x in values) + "}"
    lines = ["// Generated by extract_original_time_attack_telemetry.py; static original data.",
             "// Image SHA256 " + SHA, "#pragma once", "#include <array>", "#include <cstdint>",
             "namespace idas3::original::telemetry_data {",
             "struct Course { std::uint32_t threshold; std::array<std::uint32_t,12> corners; std::array<std::uint32_t,16> matrix; std::array<std::array<std::uint32_t,12>,3> sections; std::array<std::uint32_t,6> ranges; std::array<std::uint32_t,2> start,recordingLength; };",
             "inline constexpr std::array<Course,9> courses{{"]
    for threshold, corners, matrix, sections, ranges, start, lengths in rows:
        lines.append("{" + f"0x{threshold[0]:08x}u," + cpp(corners) + "," + cpp(matrix) + ",{{" + ",".join(cpp(x) for x in sections) + "}}," + cpp(ranges) + "," + cpp(start) + "," + cpp(lengths) + "},")
    lines.extend(["}};", "}", ""])
    output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    export(args.image, args.output)
