"""Bake only the translated save-menu glyphs from the bundled OFL fonts.

The original arcade artwork and original ASCII menu atlas are unchanged.
Source of truth for translations: Assets/Resources/Localization/CustomMenus.txt.
"""
from pathlib import Path
import struct
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

ROOT=Path(__file__).resolve().parents[2]
KEYS=['SAVE SELECT','INITIAL D / SELECT A DRIVER','USED','NEW DRIVER','EMPTY SLOT',
      'LAST USED CAR','FILE','CAR PREVIEW','PLAY TIME','LEVEL','LAST PLAYED','CONTINUE',
      'CHANGE CAR','DELETE SAVE','ARE YOU SURE?','COULD NOT DELETE SAVE','NO','YES',
      'ARROWS / STEERING','ACCEL.','Brake','SELECT','CONFIRM','BACK']
rows={row.split('\t')[0].upper():row.split('\t') for row in
      (ROOT/'Assets/Resources/Localization/CustomMenus.txt').read_text(encoding='utf-8').splitlines()
      if row and not row.startswith('#')}
selected=[['BRAKE' if key=='Brake' else key,*rows[key.upper()][1:]] for key in KEYS]
def literal(text):
    # Portable source, independent of the compiler's Windows code page.
    return '"'+''.join('\\x%02x'%b for b in text.encode('utf-8'))+'"'
header='#pragma once\n// Generated by tools/make_custom_menu_fonts.py.\n#include <array>\n#include <string_view>\nnamespace idas3 {\ninline constexpr std::array<std::array<std::string_view,3>,%d> customMenuTranslations={{\n'%len(selected)
header+=''.join('    {'+','.join(literal(t) for t in row)+'},\n' for row in selected)+'}};\n}\n'
(ROOT/'Native/src/custom_menu_text.h').write_text(header,encoding='utf-8')
out=ROOT/'Native/data/localization/custom-menus';out.mkdir(parents=True,exist_ok=True)
for index,(locale,face) in enumerate([('ja','NotoSansJP-Regular.otf'),('zh-Hans','NotoSansSC-Regular.otf')],1):
    path=ROOT/'Assets/Resources/Fonts'/face
    chars=sorted(set(''.join(row[index] for row in selected))|{chr(i) for i in range(32,127)})
    cmap=TTFont(path).getBestCmap();assert all(ord(c) in cmap for c in chars)
    font=ImageFont.truetype(str(path),42)
    cell=56;columns=24
    image=Image.new('RGBA',(columns*cell,((len(chars)+columns-1)//columns)*cell),(255,255,255,0));draw=ImageDraw.Draw(image)
    records=[]
    for n,ch in enumerate(chars):
        x,y=(n%columns)*cell,(n//columns)*cell
        draw.text((x+2,y+2),ch,font=font,anchor='lt',fill=(255,255,255,255))
        # Single common glyph top works with the existing compact save cards.
        # Use a fixed padded tile, but retain proportional Latin advance.
        records.append((ord(ch),float(x),float(y),float(cell),float(cell),font.getlength(ch)))
    blob=bytearray(b'IDMF')+struct.pack('<5I',1,image.width,image.height,48,len(records))
    for record in records:blob+=struct.pack('<I5f',*record)
    blob+=image.tobytes('raw','BGRA')
    (out/(locale+'.bin')).write_bytes(blob)
    print(locale,len(chars),'glyphs',len(blob),'bytes')
