#include "original_course_billboards.h"
#include <bit>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <string>

// The fixture contains independent SH-4 selector capture digests at every
// original authoring-path index, not values generated by this native reader.
int main(int argc,char** argv){try{
    if(argc!=3)throw std::runtime_error("asset-root source-capture-fixture required");
    std::ifstream fixture(argv[2]);if(!fixture)throw std::runtime_error("Missing source fixture");
    std::string id;unsigned night,reverse,wet,chunks,pathCount,total=0,cases=0;
    while(fixture>>id>>night>>reverse>>wet>>chunks>>pathCount){
        auto scene=idas3::OriginalCourseBillboards::load(argv[1],id,night,reverse,wet,chunks);
        for(unsigned index=0;index<pathCount;++index){
            unsigned staticCount,expected;if(!(fixture>>staticCount>>expected))throw std::runtime_error("Truncated source fixture");
            unsigned hash=2166136261u;
            const auto word=[&](unsigned value){for(unsigned i=0;i<4;++i){hash^=(value>>(i*8))&255;hash*=16777619u;}};
            for(const auto& insertion:scene.insertionsForPathIndex(index,staticCount))for(const auto& draw:insertion.assembly.instances){
                if(insertion.replaceCount||!draw.billboard)throw std::runtime_error("Incorrect native billboard flags");
                word(unsigned(insertion.before));word(draw.chunk);
                for(auto component:{3u,7u,11u})word(std::bit_cast<unsigned>(draw.transform[component]));
            }
            if(hash!=expected)throw std::runtime_error("Native/source spectator mismatch "+id+" path "+std::to_string(index));
            ++total;
        }
        ++cases;
    }
    if(!fixture.eof()||cases!=72)throw std::runtime_error("Incomplete course-condition coverage");
    std::cout<<"PASS "<<cases<<" source course conditions, "<<total<<" path selections and source insertion ordinals\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
